services:

  db:
    container_name: postgres
    image: postgres:14.13-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 738212
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin4:
    image: elestio/pgadmin:REL-8_11
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sivolobov.ilya@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 226372
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    ports:
      - "8080:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z-cpuv1
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 65732168
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-storage:
  postgres_data:
