package org.example.postgres.table;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import org.example.entity.Role;
import org.example.postgres.Config;

public class DctRolesTable {
  private static final String jdbcUrl = Config.jdbcUrl;
  private static final String username = Config.username;
  private static final String password = Config.password;

  public static void initialize() throws SQLException {
    Connection connection = DriverManager.getConnection(jdbcUrl, username, password);

    String sqlRequest =
        "DROP TABLE IF EXISTS dct.roles; "
            + "CREATE TABLE dct.roles (role_ID INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(30), PRIMARY KEY(role_ID));";
    PreparedStatement preparedStatement = connection.prepareStatement(sqlRequest);
    preparedStatement.execute();

    preparedStatement.close();
    connection.close();
  }

  public static void insert(Role role) throws SQLException {
    Connection connection = DriverManager.getConnection(jdbcUrl, username, password);

    String sqlRequest = "INSERT INTO roles(roleName) " + "VALUES (?)";
    PreparedStatement preparedStatement = connection.prepareStatement(sqlRequest);
    preparedStatement.setString(1, role.roleName());

    preparedStatement.executeUpdate();
    preparedStatement.close();
    connection.close();
  }
}
