package org.example.postgres.table;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import org.example.entity.File;
import org.example.postgres.Config;

public class FilesTable {
  private static final String jdbcUrl = Config.jdbcUrl;
  private static final String username = Config.username;
  private static final String password = Config.password;

  public static void initialize() throws SQLException {
    Connection connection = DriverManager.getConnection(jdbcUrl, username, password);

    String sqlRequest =
        "DROP TABLE IF EXISTS files; "
            + "CREATE TABLE files (file_ID INT GENERATED BY DEFAULT AS IDENTITY, created_by VARCHAR(30), updated_by VARCHAR(20), created_datetime TIMESTAMP, updated_datetime TIMESTAMP, PRIMARY KEY(file_ID)); ";
    PreparedStatement preparedStatement = connection.prepareStatement(sqlRequest);
    preparedStatement.execute();

    preparedStatement.close();
    connection.close();
  }

  public static void insert(File file) throws SQLException {
    Connection connection = DriverManager.getConnection(jdbcUrl, username, password);

    String sqlRequest =
        "INSERT INTO files(fileName, created_by, updated_by, created_datetime, updated_datetime) "
            + "VALUES (?, ?, ?, ?, ?)";
    PreparedStatement preparedStatement = connection.prepareStatement(sqlRequest);
    preparedStatement.setString(1, file.fileName());
    preparedStatement.setString(2, file.created_by());
    preparedStatement.setString(3, file.updated_by());
    preparedStatement.setDate(4, file.created_datetime());
    preparedStatement.setDate(5, file.updated_datetime());

    preparedStatement.executeUpdate();
    preparedStatement.close();
    connection.close();
  }
}
