package org.example.postgres.table;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.example.entity.User;
import org.example.postgres.Config;

public class UsersTable {
  private static final String jdbcUrl = Config.jdbcUrl;
  private static final String username = Config.username;
  private static final String password = Config.password;

  public static void initialize() throws SQLException {

    String sqlRequest =
        """
        IF NOT EXISTS users
        THEN
           CREATE TABLE users (user_ID INT GENERATED BY DEFAULT AS IDENTITY, email VARCHAR(30), password VARCHAR(20), username VARCHAR(30), PRIMARY KEY(user_ID));
        """;
    try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password);
        PreparedStatement preparedStatement = connection.prepareStatement(sqlRequest)) {
      preparedStatement.execute();
    }
  }

  public static void insert(User user) throws SQLException {

    String sqlRequest = "INSERT INTO users(email, password, username) VALUES (?, ?, ?)";

    try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password);
        PreparedStatement preparedStatement = connection.prepareStatement(sqlRequest)) {
      preparedStatement.setString(1, user.email());
      preparedStatement.setString(2, user.password());
      preparedStatement.setString(3, user.username());

      preparedStatement.executeUpdate();
    }
  }

  public static boolean exists(String email) throws SQLException {

    String sqlRequest =
        String.format("SELECT COUNT(email) AS total FROM users WHERE email = '%s'", email);
    try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password);
        PreparedStatement preparedStatement = connection.prepareStatement(sqlRequest);
        ResultSet rs = preparedStatement.executeQuery()) {
      rs.next();
      int result = rs.getInt("total");
      return result != 0;
    }
  }

  public static String getUserPassword(String email) throws SQLException {
    String sqlRequest = String.format("SELECT password FROM users WHERE email = '%s'", email);
    try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password);
        PreparedStatement preparedStatement = connection.prepareStatement(sqlRequest);
        ResultSet rs = preparedStatement.executeQuery()) {
      String result = "";
      while (rs.next()) {
        result = rs.getString(1);
      }
      return result;
    }
  }
}
