package org.app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Postgres {

  private static final String jdbcUrl = "jdbc:postgresql://localhost:5432/postgres";
  private static final String username = "postgres";
  private static final String password = "738212";

  public static ResultSet select(String id) throws SQLException {
    final String selectQuery = "SELECT file_owner, created_date, last_update, tags, access_rights FROM FileInfo WHERE Id = ?";

    try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password);
        PreparedStatement preparedStatement = connection.prepareStatement(selectQuery);
    ) {

      preparedStatement.setString(1, id);

      try (ResultSet resultSet = preparedStatement.executeQuery();) {
        return resultSet;
      }
    }
  }

  public static void initializeDb() throws SQLException {
    final String sqlRequest =
        "DROP TABLE IF EXISTS FileInfo; "
            + "CREATE TABLE FileInfo (Id SERIAL GENERATED BY DEFAULT AS IDENTITY, file_owner STRING(30), created_date STRING(10), last_update STRING(10), tags STRING(100), access_rights STRING(10));";

    try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password);
        PreparedStatement preparedStatement = connection.prepareStatement(sqlRequest);
    ) {

      preparedStatement.execute();

    }
  }
}